# Auto Build & Release (Web + Android)
# - يَشغّل على push إلى main أو عند إنشاء tag (v*)
# - ينشئ draft release ويحفظ artifacts داخل release/
# - يحاول بناء الويب والـ Android (إن وُجد مجلد android/)
# ملاحظة: عدّل أو أضف أسرار/متغيرات المستودع حسب الحاجة (VITE_CONVEX_URL وAndroid keystore secrets)
name: Auto Build & Release (Web + Android)

on:
  push:
    branches: [main]
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  build-and-release:
    name: Build, package and publish release
    runs-on: ubuntu-latest
    environment: github-actions
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies (allow creating lockfile)
        run: |
          bun --version || true
          bun install || true

      - name: Generate icons
        run: bun run icons || true

      - name: Typecheck
        run: bun run typecheck || true

      - name: Build web PWA
        run: |
          VITE_CONVEX_URL=${{ vars.VITE_CONVEX_URL }} bun run build
        env:
          VITE_CONVEX_URL: ${{ vars.VITE_CONVEX_URL }}

      - name: Prepare release directory
        run: |
          rm -rf release || true
          mkdir -p release/web-pwa
          cp -r dist release/web-pwa || true

      - name: Package web artifacts
        run: |
          cd release
          zip -r "vip-yemen-web-pwa-${{ github.ref_name || github.run_id }}.zip" web-pwa || true
          cd ..

      - name: Optionally build Android (if android/ exists)
        run: |
          if [ -d android ]; then
            echo "Android directory found — building APK/AAB"
            sudo apt-get update && sudo apt-get install -y zip unzip || true
            cd android
            chmod +x gradlew || true
            ./gradlew assembleRelease bundleRelease --no-daemon || true
            mv app/build/outputs/apk/release/app-release.apk app/build/outputs/apk/release/vip-yemen-android-${{ github.ref_name || github.run_id }}.apk || true
            mv app/build/outputs/bundle/release/app-release.aab app/build/outputs/bundle/release/vip-yemen-android-${{ github.ref_name || github.run_id }}.aab || true
            cd ..
            mkdir -p release/android
            cp android/app/build/outputs/apk/release/*.apk release/android/ 2>/dev/null || true
            cp android/app/build/outputs/bundle/release/*.aab release/android/ 2>/dev/null || true
          else
            echo "No android directory — skipping Android build"
          fi

      - name: Include additional docs and assets (if present)
        run: |
          cp PRIVACY-POLICY.md PRIVACY-POLICY-APP.md PUBLISHING-GUIDE.md RELEASE-GUIDE.md OPERATIONS-GUIDE.md SIGNING-AND-OWNERSHIP.md README.md store-listing.json release/ 2>/dev/null || true
          cp store-graphics/*.png release/ 2>/dev/null || true

      - name: Create draft GitHub release with artifacts
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name || format('auto-%s', github.run_id) }}
          name: "ViP Yemen Release ${{ github.ref_name || github.run_id }}"
          body: |
            Automated release generated by workflow ${{ github.workflow }} (run id ${{ github.run_id }}).

            Includes web PWA and platform artifacts when built.
          files: |
            release/*
          draft: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload release artifacts to workflow (fallback)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: release-artifacts-${{ github.run_id }}
          path: release/
